name: Gitleaks Secret Scan

on: [push, pull_request]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks
        continue-on-error: true
        run: |
          gitleaks detect --source=. --report-format=json --report-path=gitleaks-report.json

      - name: Check for Secrets & Notify Discord
        if: always()
        run: |
          if [ -s gitleaks-report.json ]; then
            PAYLOAD='{
              "content": "🚨 **Secret Leak Detected in PR!** 🔒",
              "embeds": [
                {
                  "title": "Gitleaks Found Secrets",
                  "description": "Secrets detected in `${{ github.repository }}`",
                  "color": 16711680,
                  "fields": [
                    {
                      "name": "🔗 Pull Request",
                      "value": "[View PR](https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }})",
                      "inline": true
                    },
                    {
                      "name": "🛑 Action Required",
                      "value": "Please review and remove secrets before merging.",
                      "inline": false
                    }
                  ]
                }
              ]
            }'
            curl -X POST -H 'Content-Type: application/json' --data "$PAYLOAD" "https://discord.com/api/webhooks/${{ secrets.DISCORD_WEBHOOK }}"
            echo "::error::Secrets detected in the PR. Check Discord notification for details."
            exit 1
          fi

      - name: Upload Gitleaks Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
